
# Jekyll Configuration
safe: true
markdown: rdiscount
permalink: pretty
lsi: false

# Site
name: Human Development Index Explorer
baseurl: http://pnavarrc.github.io/hdi-explorer
github: http://github.com/pnavarrc/hdi-explorer.git
