# Jekyll Configuration
safe: true
markdown: rdiscount
permalink: pretty
exclude: ['bower_components', 'node_modules']

# Site
name: Human Development Index Explorer
baseurl: http://pnavarrc.github.io/hdi-explorer
github: http://github.com/pnavarrc/hdi-explorer.git
